# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment the following line to enable the Sofle OLED Display
# CONFIG_ZMK_DISPLAY=y

# Uncomment these two lines to add support for encoders
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment this line below to add rgb underglow / backlight support
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_KEYBOARD_NAME="ChosenOne"

# 摇杆驱动
CONFIG_JOYSTICK_MOUSE=y
CONFIG_JOYSTICK_ALWAYS_ACTIVE=y
CONFIG_JOYSTICK_POLLING_INTERVAL=20
CONFIG_JOYSTICK_DEADZONE=100
CONFIG_JOYSTICK_SENSITIVITY=5
CONFIG_JOYSTICK_INVERT_Y=n

# ADC配置
CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y
CONFIG_ADC_NRFX_SAADC_LP_MODE=n
CONFIG_ADC_ASYNC=y
CONFIG_ADC_BUFFER_SIZE=2

# 鼠标HID
CONFIG_ZMK_HID_REPORT_TYPE_HIDMOUSE=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_MOUSE_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_MOUSE_TICK_DURATION=8

# 行为
CONFIG_ZMK_BEHAVIORS=y
CONFIG_ZMK_BEHAVIOR_JOYSTICK=y

# 蓝牙和USB
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_LOGGING=y

# 电源管理
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# 调试
CONFIG_ZMK_LOG_LEVEL_INF=y
CONFIG_JOYSTICK_LOG_LEVEL_DBG=y
CONFIG_ADC_LOG_LEVEL_WRN=y
